### ISSUE TITLE
[Bug] Undercut scanning sometimes randomly stops.

### ISSUE THREAD

**Issue by zeenk** [Auctionator/Auctionator#1186]
Not sure what I did to trigger this but got this error, using latest alpha version.

Edit: Seems to be a pretty rare error, doesn't happen very often and just re-opening ah and undercut scan again usually fixes it.

Message: ...rce_Mainline\Tabs\Cancelling\Mixins\UndercutScan.lua:173: attempt to index local 'itemKeyInfo' (a nil value)
Time: Wed Aug 31 06:21:19 2022
Count: 1
Stack: ...rce_Mainline\Tabs\Cancelling\Mixins\UndercutScan.lua:173: attempt to index local 'itemKeyInfo' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Auctionator\Source_Mainline\Tabs\Cancelling\Mixins\UndercutScan.lua"]:173: in function `ProcessSearchResults'
[string "@Interface\AddOns\Auctionator\Source_Mainline\Tabs\Cancelling\Mixins\UndercutScan.lua"]:133: in function <...rce_Mainline\Tabs\Cancelling\Mixins\UndercutScan.lua:112>

Locals:

**Comment by zeenk** [comment]
I've noticed when doing the undercut scan it sometimes randomly stops but it doesn't always trigger the lua error 🤔 

![2022-09-01_18-15-36](https://user-images.githubusercontent.com/68170439/187963101-b1f01478-e891-4233-a558-bcfe1e66edd4.png)

**Comment by plusmouse** [comment]
I think I've fixed this problem in the latest alpha
[Auctionator-9.2.33-1-g18d5240.zip](https://github.com/Auctionator/Auctionator/files/9482178/Auctionator-9.2.33-1-g18d5240.zip)

**Comment by zeenk** [comment]
Didn't quite fix it, still happening but didn't get a lua pop up this time, the 2 buttons at bottom right are greyed out so can't refresh it have to close ah and re-open it then it works again, but it's better now at least doesn't happen as often.

![2022-09-03_20-16-14](https://user-images.githubusercontent.com/68170439/188283313-2142e833-2986-4b2f-8ae4-bb62c4edb161.png)

**Comment by zeenk** [comment]
Just a lil vid to show what's happening

https://user-images.githubusercontent.com/68170439/188284401-d35d31af-eb3d-4245-85ba-09027f97973c.mp4

**Comment by zeenk** [comment]
Could it have something to do with #1163 ? just saw my file was starting to get large again, maybe something doesn't load properly or something 🤔 

![2022-09-04_00-06-02](https://user-images.githubusercontent.com/68170439/188289020-6604445b-5209-4fc5-a4ba-88e0b3c3afe3.png)

**Comment by zeenk** [comment]
The lua error itself seem to have been fixed, haven't had any more pop ups since the alpha update but the bug itself still remains so changed title for this issue.

**Comment by zeenk** [comment]
Gonna close this issue for now, haven't ran into this bug now for almost 24 hours so just gonna assume it was something else that was causing the scan to randomly stop since I seem to be the only one experiencing this, re-opening if it happens again.
