### ISSUE TITLE
Not Working for Classic Era

### ISSUE THREAD

**Issue by maximus210793** [Auctionator/Auctionator#1331]
Hi,
since the last Blizzard Update the addon is no longer working for Classic Era.
So the addon is no longer displaying when pressing the "selling" button in the auction house tap, the items you have in your bags for selling.
<img width="758" alt="image" src="https://user-images.githubusercontent.com/76915579/213873166-f0399ce0-b529-4c02-963b-b48ef15973d7.png">

A fix would be awesome.
Thanks a lot!

**Comment by plusmouse** [comment]
It should be working with the latest release.
![image](https://user-images.githubusercontent.com/60280559/213879055-dd639507-042b-4bb3-bdb5-63d06ae3813e.png)

**Comment by maximus210793** [comment]
Still not working, do you know if it interfers with other addons?

**Comment by maximus210793** [comment]
Update:
When I disable the addon RC Loot Council (https://www.curseforge.com/wow/addons/rclootcouncil-classic) the problem is solved.
Could you please check if Auctionator causes the problems in combination.
Thanks in advance!

**Comment by plusmouse** [comment]
Tried installing RC Loot Council, no issues.

**Comment by maximus210793** [comment]
So strange the different behavior...
