### ISSUE TITLE
Not recognizing different crafted item suffixes when checking for undercuts (More tab)

### ISSUE THREAD

**Issue by alexreidperc** [Auctionator/Auctionator#215]
Please include as much of the following information as possible to help me fix the bug:

Addon is not differentiating between crafted items with different suffixes when checking for undercuts. For example for the item "Gravenscale Grips of the Feverflare", it will search for that particular item but also include all of the other types in the same search ("Grips of the Peerless", etc.). This causes a massive problem because you can only see one type of the crafted items being undercut at once, and have to go in manually to check prices on the others.

_Please include a brief description of the bug, including what you were doing, and when it occurred._
## Steps to Reproduce

_Include the steps I would need to follow to reproduce the bug._
## Loaded Addons

_Include a list of addons you were running at the time this bug occurred._
## Back Trace (LUA Error Output)

_You can get this through the use of !BugGrabber and BugSack addons._

**Comment by ceylina** [comment]
Issues with crafted items was fixed in 4.0.12 and item level fix was added with 4.0.13

Make sure you have the latest version. 

Cannot reproduce with latest version

**Comment by alexreidperc** [comment]
Confirmed I have 4.0.13 and it is still not differentiating between crafted
items with the same name but different suffix.

It's still lumping all of the same type of crafted items together when I go
to scan for undercuts. I don't want my Gravenscale Grips of the harmonious
to show up on the same line as say a Gravenscale Grips of the Feverflare.
It's only giving me information on one of the types of the item even when I
have 5-6 different kinds posted. Is there some way to separate between
these I'm missing? Have tried digging through to find a solution with no
luck.

Thanks for making such an awesome add on by the way. I really appreciate it.

**Comment by jrob8577** [comment]
@alexreidperc Apologies, I haven't been playing the AH much yet - are these items (gravenscale) legion, or pre-legion crafted items?

**Comment by jrob8577** [comment]
@alexreidperc nvm, I see they're legion, just took a quick trip to AH.  :P  This is only when you sell? I checked the Buy tab and I'm seeing different items by suffix, but will need to level a toon to craft some stuff to be able to test this for selling...

**Comment by alexreidperc** [comment]
The ones I used as an example are the Legion  leatherworking crafted items.
They are called "Gravenscale Armbands" and when they're crafted are named
"of the" and given a descriptive word  (Feverflare, peerless, etc) based on
which stats they roll.

I can't seem to get auctionator to differentiate between them past the
initial name- for example Gravenscale Armbands of all types show up in the
same line in the More... tab. They vary in value depending on their stats
so it's important to be able to check them against each other individually.

Thanks for the responses!

**Comment by ceylina** [comment]
Apologies for closing this. Looks like I missed a key detail. We will have to look into the functionality of the more tab and see if it is not registering the bonus id changes we did for searches

**Comment by ceylina** [comment]
Please confirm this is the issue you are seeing:

I placed two items of different "of the" names on the AH

![wowscrnshot_091216_095405](https://cloud.githubusercontent.com/assets/9342192/18440522/12708cf2-78cf-11e6-9d46-3e1149ff4a6b.jpg)


In the more tab, only one is showing

![wowscrnshot_091216_095414](https://cloud.githubusercontent.com/assets/9342192/18440529/1c524c38-78cf-11e6-93f1-38b9fb18e41b.jpg)

**Comment by ceylina** [comment]
This may also apply to sell tab as well. Will need to research
