### ISSUE TITLE
Undercut scanning - list keeps re-sorting itself when sorting list by "undercut?"

### ISSUE THREAD

**Issue by addonaddict** [Auctionator/Auctionator#971]
Only Auctionator loaded:

When doing undercut scan WHILE sorting by whether it is undercut or not, clicking to cancel an item makes the list re-sort itself
Ideally, the list should remain as it was, with items BELOW it pushed up in the missing spot
This is very frustrating when you have items that you cannot cancel because addon doesnt recognize items you posted at higher price than a random super low price
This issue is somewhat related to this feature request: Feature Request: ignore item at undercut scan #970

Can replicate by run cancel scan, sort by undercut? top down and start cancelling by clicking on items
Happens with no other addons on, fresh wow install

Thank you

at start, sorted by "undercut?" from top down:
![image](https://user-images.githubusercontent.com/73442541/104140185-1fd57680-537e-11eb-86f3-6dd171d5e005.png)
after cancelling bottom-most item by clicking on it directly
![image](https://user-images.githubusercontent.com/73442541/104140188-2663ee00-537e-11eb-90d3-ecb1f5fe2b7c.png)

**Comment by plusmouse** [comment]
Should be fixed in alpha 460

**Comment by addonaddict** [comment]
latest alpha 468 has this problem still, although seemingly in a lesser form
items for some reason still re-sort, at least once per cancel scan
soon as i finish a cancel scan, the first item i de-list refreshes the whole list
this needs more testing, but the sorting issue is there 100%, just cant pin point how often it happens as its seemingly random

**Comment by plusmouse** [comment]
Its associated with having TSM installed - TSM does a background query every time an auction is cancelled, and that is causing the extra refresh/reorder - as the code in Auctionator assumes there are no extra queries.
